# Generated by Django 3.2.20 on 2023-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_auto_20230827_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='order_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_category',
            field=models.CharField(choices=[('general', 'General Admission'), ('grandstand', 'Grandstand Seat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_type',
            field=models.CharField(choices=[('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('all', 'All 3 Days')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
